package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * AgrupacionDocumento generated by hbm2java
 */
public class AgrupacionDocumento  implements java.io.Serializable {


     private AgrupacionDocumentoId id;

    public AgrupacionDocumento() {
    }

    public AgrupacionDocumento(AgrupacionDocumentoId id) {
       this.id = id;
    }
   
    public AgrupacionDocumentoId getId() {
        return this.id;
    }
    
    public void setId(AgrupacionDocumentoId id) {
        this.id = id;
    }




}


