package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * AgrupacionDocumentoId generated by hbm2java
 */
public class AgrupacionDocumentoId  implements java.io.Serializable {


     private int tmDocumentoId;
     private int tmStakeAgrupacionId;

    public AgrupacionDocumentoId() {
    }

    public AgrupacionDocumentoId(int tmDocumentoId, int tmStakeAgrupacionId) {
       this.tmDocumentoId = tmDocumentoId;
       this.tmStakeAgrupacionId = tmStakeAgrupacionId;
    }
   
    public int getTmDocumentoId() {
        return this.tmDocumentoId;
    }
    
    public void setTmDocumentoId(int tmDocumentoId) {
        this.tmDocumentoId = tmDocumentoId;
    }
    public int getTmStakeAgrupacionId() {
        return this.tmStakeAgrupacionId;
    }
    
    public void setTmStakeAgrupacionId(int tmStakeAgrupacionId) {
        this.tmStakeAgrupacionId = tmStakeAgrupacionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgrupacionDocumentoId) ) return false;
		 AgrupacionDocumentoId castOther = ( AgrupacionDocumentoId ) other; 
         
		 return (this.getTmDocumentoId()==castOther.getTmDocumentoId())
 && (this.getTmStakeAgrupacionId()==castOther.getTmStakeAgrupacionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTmDocumentoId();
         result = 37 * result + this.getTmStakeAgrupacionId();
         return result;
   }   


}


