package celepsa.rrcc.eh;
// Generated 17/07/2014 10:17:45 PM by Hibernate Tools 3.6.0



/**
 * AgrupacionDocumentoId generated by hbm2java
 */
public class AgrupacionDocumentoId  implements java.io.Serializable {


     private int tmDocumentoId;
     private int tmStakeAgrupacionId;

    public AgrupacionDocumentoId() {
    }

    public AgrupacionDocumentoId(int tmDocumentoId, int tmStakeAgrupacionId) {
       this.tmDocumentoId = tmDocumentoId;
       this.tmStakeAgrupacionId = tmStakeAgrupacionId;
    }
   
    public int getTmDocumentoId() {
        return this.tmDocumentoId;
    }
    
    public void setTmDocumentoId(int tmDocumentoId) {
        this.tmDocumentoId = tmDocumentoId;
    }
    public int getTmStakeAgrupacionId() {
        return this.tmStakeAgrupacionId;
    }
    
    public void setTmStakeAgrupacionId(int tmStakeAgrupacionId) {
        this.tmStakeAgrupacionId = tmStakeAgrupacionId;
    }




}


