package celepsa.rrcc.eh;
// Generated 17/07/2014 10:17:45 PM by Hibernate Tools 3.6.0



/**
 * PersonaDocumentoId generated by hbm2java
 */
public class PersonaDocumentoId  implements java.io.Serializable {


     private int tmDocumentoId;
     private int tmStakePersonaId;

    public PersonaDocumentoId() {
    }

    public PersonaDocumentoId(int tmDocumentoId, int tmStakePersonaId) {
       this.tmDocumentoId = tmDocumentoId;
       this.tmStakePersonaId = tmStakePersonaId;
    }
   
    public int getTmDocumentoId() {
        return this.tmDocumentoId;
    }
    
    public void setTmDocumentoId(int tmDocumentoId) {
        this.tmDocumentoId = tmDocumentoId;
    }
    public int getTmStakePersonaId() {
        return this.tmStakePersonaId;
    }
    
    public void setTmStakePersonaId(int tmStakePersonaId) {
        this.tmStakePersonaId = tmStakePersonaId;
    }




}


