package celepsa.rrcc.eh;
// Generated 17/07/2014 10:17:45 PM by Hibernate Tools 3.6.0



/**
 * PersonaDocumento generated by hbm2java
 */
public class PersonaDocumento  implements java.io.Serializable {


     private PersonaDocumentoId id;

    public PersonaDocumento() {
    }

    public PersonaDocumento(PersonaDocumentoId id) {
       this.id = id;
    }
   
    public PersonaDocumentoId getId() {
        return this.id;
    }
    
    public void setId(PersonaDocumentoId id) {
        this.id = id;
    }




}


