package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * PersonaDocumentoId generated by hbm2java
 */
public class PersonaDocumentoId  implements java.io.Serializable {


     private int tmDocumentoId;
     private int tmStakePersonaId;

    public PersonaDocumentoId() {
    }

    public PersonaDocumentoId(int tmDocumentoId, int tmStakePersonaId) {
       this.tmDocumentoId = tmDocumentoId;
       this.tmStakePersonaId = tmStakePersonaId;
    }
   
    public int getTmDocumentoId() {
        return this.tmDocumentoId;
    }
    
    public void setTmDocumentoId(int tmDocumentoId) {
        this.tmDocumentoId = tmDocumentoId;
    }
    public int getTmStakePersonaId() {
        return this.tmStakePersonaId;
    }
    
    public void setTmStakePersonaId(int tmStakePersonaId) {
        this.tmStakePersonaId = tmStakePersonaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonaDocumentoId) ) return false;
		 PersonaDocumentoId castOther = ( PersonaDocumentoId ) other; 
         
		 return (this.getTmDocumentoId()==castOther.getTmDocumentoId())
 && (this.getTmStakePersonaId()==castOther.getTmStakePersonaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTmDocumentoId();
         result = 37 * result + this.getTmStakePersonaId();
         return result;
   }   


}


