package celepsa.rrcc.eh;
// Generated 17/07/2014 10:17:45 PM by Hibernate Tools 3.6.0



/**
 * TmAdjuntoId generated by hbm2java
 */
public class TmAdjuntoId  implements java.io.Serializable {


     private int id;
     private int tmDocumentoId;

    public TmAdjuntoId() {
    }

    public TmAdjuntoId(int id, int tmDocumentoId) {
       this.id = id;
       this.tmDocumentoId = tmDocumentoId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getTmDocumentoId() {
        return this.tmDocumentoId;
    }
    
    public void setTmDocumentoId(int tmDocumentoId) {
        this.tmDocumentoId = tmDocumentoId;
    }




}


