package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * TmAdjunto generated by hbm2java
 */
public class TmAdjunto  implements java.io.Serializable {


     private TmAdjuntoId id;
     private String nombre;
     private Character eliminado;
     private String scodigo;

    public TmAdjunto() {
    }

	
    public TmAdjunto(TmAdjuntoId id) {
        this.id = id;
    }
    public TmAdjunto(TmAdjuntoId id, String nombre, Character eliminado, String scodigo) {
       this.id = id;
       this.nombre = nombre;
       this.eliminado = eliminado;
       this.scodigo = scodigo;
    }
   
    public TmAdjuntoId getId() {
        return this.id;
    }
    
    public void setId(TmAdjuntoId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Character getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(Character eliminado) {
        this.eliminado = eliminado;
    }
    public String getScodigo() {
        return this.scodigo;
    }
    
    public void setScodigo(String scodigo) {
        this.scodigo = scodigo;
    }




}


