package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * TmAdjuntoId generated by hbm2java
 */
public class TmAdjuntoId  implements java.io.Serializable {


     private int id;
     private int tmDocumentoId;

    public TmAdjuntoId() {
    }

    public TmAdjuntoId(int id, int tmDocumentoId) {
       this.id = id;
       this.tmDocumentoId = tmDocumentoId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getTmDocumentoId() {
        return this.tmDocumentoId;
    }
    
    public void setTmDocumentoId(int tmDocumentoId) {
        this.tmDocumentoId = tmDocumentoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmAdjuntoId) ) return false;
		 TmAdjuntoId castOther = ( TmAdjuntoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getTmDocumentoId()==castOther.getTmDocumentoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getTmDocumentoId();
         return result;
   }   


}


