package celepsa.rrcc.eh;
// Generated 17/07/2014 10:17:45 PM by Hibernate Tools 3.6.0



/**
 * TmClimaId generated by hbm2java
 */
public class TmClimaId  implements java.io.Serializable {


     private int tmZonaId;
     private String fechaGeneracion;

    public TmClimaId() {
    }

    public TmClimaId(int tmZonaId, String fechaGeneracion) {
       this.tmZonaId = tmZonaId;
       this.fechaGeneracion = fechaGeneracion;
    }
   
    public int getTmZonaId() {
        return this.tmZonaId;
    }
    
    public void setTmZonaId(int tmZonaId) {
        this.tmZonaId = tmZonaId;
    }
    public String getFechaGeneracion() {
        return this.fechaGeneracion;
    }
    
    public void setFechaGeneracion(String fechaGeneracion) {
        this.fechaGeneracion = fechaGeneracion;
    }




}


