package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * TmClimaId generated by hbm2java
 */
public class TmClimaId  implements java.io.Serializable {


     private TmZona tmZonaId;
     private String fechaGeneracion;

    public TmClimaId() {
    }

    public TmClimaId(TmZona tmZonaId, String fechaGeneracion) {
       this.tmZonaId = tmZonaId;
       this.fechaGeneracion = fechaGeneracion;
    }
   
    public TmZona getTmZonaId() {
        return this.tmZonaId;
    }
    
    public void setTmZonaId(TmZona tmZonaId) {
        this.tmZonaId = tmZonaId;
    }
    public String getFechaGeneracion() {
        return this.fechaGeneracion;
    }
    
    public void setFechaGeneracion(String fechaGeneracion) {
        this.fechaGeneracion = fechaGeneracion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmClimaId) ) return false;
		 TmClimaId castOther = ( TmClimaId ) other; 
         
		 return (this.getTmZonaId()==castOther.getTmZonaId())
 && ( (this.getFechaGeneracion()==castOther.getFechaGeneracion()) || ( this.getFechaGeneracion()!=null && castOther.getFechaGeneracion()!=null && this.getFechaGeneracion().equals(castOther.getFechaGeneracion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTmZonaId().getId();
         result = 37 * result + ( getFechaGeneracion() == null ? 0 : this.getFechaGeneracion().hashCode() );
         return result;
   }   


}


