package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * TmDocumento generated by hbm2java
 */
public class TmDocumento  implements java.io.Serializable {


     private int id;
     private String fechaRegistro;
     private String fechaRecepcion;
     private String fechaCaducidad;
     private String asunto;
     private String observaciones;
     private Integer ingresoSalida;
     private Integer tmStakePersonaId;
     private Integer tmTipoDocumentoId;
     private Integer refConvenio;
     private Integer refPrograma;
     private Integer refProyecto;
     private Integer refDocumento;
     private Integer criticidadId;
     private Character eliminado;
     private int tmEstadoId;

    public TmDocumento() {
    }

	
    public TmDocumento(int id, int tmEstadoId) {
        this.id = id;
        this.tmEstadoId = tmEstadoId;
    }
    public TmDocumento(int id, String fechaRegistro, String fechaRecepcion, String fechaCaducidad, String asunto, String observaciones, Integer ingresoSalida, Integer tmStakePersonaId, Integer tmTipoDocumentoId, Integer refConvenio, Integer refPrograma, Integer refProyecto, Integer refDocumento, Integer criticidadId, Character eliminado, int tmEstadoId) {
       this.id = id;
       this.fechaRegistro = fechaRegistro;
       this.fechaRecepcion = fechaRecepcion;
       this.fechaCaducidad = fechaCaducidad;
       this.asunto = asunto;
       this.observaciones = observaciones;
       this.ingresoSalida = ingresoSalida;
       this.tmStakePersonaId = tmStakePersonaId;
       this.tmTipoDocumentoId = tmTipoDocumentoId;
       this.refConvenio = refConvenio;
       this.refPrograma = refPrograma;
       this.refProyecto = refProyecto;
       this.refDocumento = refDocumento;
       this.criticidadId = criticidadId;
       this.eliminado = eliminado;
       this.tmEstadoId = tmEstadoId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(String fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(String fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Integer getIngresoSalida() {
        return this.ingresoSalida;
    }
    
    public void setIngresoSalida(Integer ingresoSalida) {
        this.ingresoSalida = ingresoSalida;
    }
    public Integer getTmStakePersonaId() {
        return this.tmStakePersonaId;
    }
    
    public void setTmStakePersonaId(Integer tmStakePersonaId) {
        this.tmStakePersonaId = tmStakePersonaId;
    }
    public Integer getTmTipoDocumentoId() {
        return this.tmTipoDocumentoId;
    }
    
    public void setTmTipoDocumentoId(Integer tmTipoDocumentoId) {
        this.tmTipoDocumentoId = tmTipoDocumentoId;
    }
    public Integer getRefConvenio() {
        return this.refConvenio;
    }
    
    public void setRefConvenio(Integer refConvenio) {
        this.refConvenio = refConvenio;
    }
    public Integer getRefPrograma() {
        return this.refPrograma;
    }
    
    public void setRefPrograma(Integer refPrograma) {
        this.refPrograma = refPrograma;
    }
    public Integer getRefProyecto() {
        return this.refProyecto;
    }
    
    public void setRefProyecto(Integer refProyecto) {
        this.refProyecto = refProyecto;
    }
    public Integer getRefDocumento() {
        return this.refDocumento;
    }
    
    public void setRefDocumento(Integer refDocumento) {
        this.refDocumento = refDocumento;
    }
    public Integer getCriticidadId() {
        return this.criticidadId;
    }
    
    public void setCriticidadId(Integer criticidadId) {
        this.criticidadId = criticidadId;
    }
    public Character getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(Character eliminado) {
        this.eliminado = eliminado;
    }
    public int getTmEstadoId() {
        return this.tmEstadoId;
    }
    
    public void setTmEstadoId(int tmEstadoId) {
        this.tmEstadoId = tmEstadoId;
    }




}


