package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * TmNivelInfluencia generated by hbm2java
 */
public class TmNivelInfluencia  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private String est;

    public TmNivelInfluencia() {
    }

	
    public TmNivelInfluencia(int id) {
        this.id = id;
    }
    public TmNivelInfluencia(int id, String descripcion, String est) {
       this.id = id;
       this.descripcion = descripcion;
       this.est = est;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEst() {
        return this.est;
    }
    
    public void setEst(String est) {
        this.est = est;
    }




}


