package celepsa.rrcc.eh;
// Generated 15-jul-2014 15:31:34 by Hibernate Tools 3.6.0



/**
 * TmStakePersona generated by hbm2java
 */
public class TmStakePersona  implements java.io.Serializable {


     private int id;
     private String fechaRegistro;
     private String nombre;
     private String apellido;
     private String alias;
     private String identidad;
     private String nroDocumento;
     private int tmTdocumentoId;
     private String fotografia;
     private int tmNivelInfluenciaId;
     private Integer est;
     private int tmZonaId;
     private int tmEstadoId;

    public TmStakePersona() {
    }

	
    public TmStakePersona(int id, int tmTdocumentoId, int tmNivelInfluenciaId, int tmZonaId, int tmEstadoId) {
        this.id = id;
        this.tmTdocumentoId = tmTdocumentoId;
        this.tmNivelInfluenciaId = tmNivelInfluenciaId;
        this.tmZonaId = tmZonaId;
        this.tmEstadoId = tmEstadoId;
    }
    public TmStakePersona(int id, String fechaRegistro, String nombre, String apellido, String alias, String identidad, String nroDocumento, int tmTdocumentoId, String fotografia, int tmNivelInfluenciaId, Integer est, int tmZonaId, int tmEstadoId) {
       this.id = id;
       this.fechaRegistro = fechaRegistro;
       this.nombre = nombre;
       this.apellido = apellido;
       this.alias = alias;
       this.identidad = identidad;
       this.nroDocumento = nroDocumento;
       this.tmTdocumentoId = tmTdocumentoId;
       this.fotografia = fotografia;
       this.tmNivelInfluenciaId = tmNivelInfluenciaId;
       this.est = est;
       this.tmZonaId = tmZonaId;
       this.tmEstadoId = tmEstadoId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getIdentidad() {
        return this.identidad;
    }
    
    public void setIdentidad(String identidad) {
        this.identidad = identidad;
    }
    public String getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(String nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
    public int getTmTdocumentoId() {
        return this.tmTdocumentoId;
    }
    
    public void setTmTdocumentoId(int tmTdocumentoId) {
        this.tmTdocumentoId = tmTdocumentoId;
    }
    public String getFotografia() {
        return this.fotografia;
    }
    
    public void setFotografia(String fotografia) {
        this.fotografia = fotografia;
    }
    public int getTmNivelInfluenciaId() {
        return this.tmNivelInfluenciaId;
    }
    
    public void setTmNivelInfluenciaId(int tmNivelInfluenciaId) {
        this.tmNivelInfluenciaId = tmNivelInfluenciaId;
    }
    public Integer getEst() {
        return this.est;
    }
    
    public void setEst(Integer est) {
        this.est = est;
    }
    public int getTmZonaId() {
        return this.tmZonaId;
    }
    
    public void setTmZonaId(int tmZonaId) {
        this.tmZonaId = tmZonaId;
    }
    public int getTmEstadoId() {
        return this.tmEstadoId;
    }
    
    public void setTmEstadoId(int tmEstadoId) {
        this.tmEstadoId = tmEstadoId;
    }




}


