package celepsa.rrcc.eh;
// Generated 17/07/2014 10:17:45 PM by Hibernate Tools 3.6.0



/**
 * TmZona generated by hbm2java
 */
public class TmZona  implements java.io.Serializable {


     private int id;
     private String descripcion;

    public TmZona() {
    }

	
    public TmZona(int id) {
        this.id = id;
    }
    public TmZona(int id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


